"""
make_tables.py -- generate the collapse and negative-result tables from measured results.

Every number in the generated tables comes from a JSON file written by an
experiment script.  Nothing is typed by hand, so a value in the PDF always
corresponds to a run that actually happened.

    python tools/make_tables.py --results results --out out/tables

Emits into out/tables/:
    collapse.tex        the headline collapse measurement
    negative.tex        the band-tiling negative result
"""

import argparse
import json
import os

# ----------------------------------------------------------------------

def load(path):
    return json.load(open(path)) if os.path.exists(path) else None


def pct(v, nd=1):
    return "--" if v is None else ("%." + str(nd) + "f") % (100.0 * v)


def num(v, nd=3):
    return "--" if v is None else ("%." + str(nd) + "f") % v


def pval(p):
    if p is None or p != p:
        return "--"
    return "$<$0.001" if p < 1e-3 else "%.3f" % p


# ----------------------------------------------------------------------
# Table 1 -- the collapse measurement (the headline)
# ----------------------------------------------------------------------

COLLAPSE_ROWS = [
    ("original", "Referenced STLAT", "shared", "static"),
    ("original_unshared", "\\quad + separate $W_x$", "separate", "static"),
    ("original_asfg", "Referenced STLAT + ASFG", "shared", "ASFG"),
    ("original_asfg_unshared", "\\quad + separate $W_x$", "separate", "ASFG"),
]


def table_collapse(pos):
    a = pos["arms"]
    L = ["% AUTO-GENERATED by tools/make_tables.py -- do not edit",
         "\\begin{table}[htb]", "\\centering",
         "\\caption{Memory collapse in the referenced STLAT architecture, measured "
         "after training on the two-cue task of Section~\\ref{sec:synthetic} "
         "($\\tau_s{=}2$, $\\tau_l{=}16$), mean over %d seeds. OVL is the overlap "
         "of the two streams' realised $\\ln\\tau_{\\mathrm{eff}}$ distributions "
         "($0$ = disjoint, $1$ = indistinguishable); $L_{\\mathrm{dec}}$ is "
         "chance-corrected cross-stream coherence; ER is effective rank as a "
         "fraction of its maximum, where $0.5$ would mean two streams span one "
         "stream's worth of directions. Sharing the input projections is the "
         "condition Proposition~\\ref{prop:collapse} identifies, and the measured "
         "overlap follows it.}" % len(pos["seeds"]),
         "\\label{tab:collapse}", "\\footnotesize",
         "\\begin{tabular}{@{}llcccc@{}}", "\\toprule",
         "\\textbf{Configuration} & $\\boldsymbol{W_x}$ & "
         "\\textbf{OVL}~$\\downarrow$ & $\\boldsymbol{L_{\\mathrm{dec}}}$~$\\downarrow$ & "
         "\\textbf{ER}~$\\uparrow$ & \\textbf{Acc.\\,\\%}\\\\", "\\midrule"]

    # Only the four referenced-model configurations belong in this table; the
    # exploratory arms live in the negative-result section.
    WANT = ["original", "original_unshared", "original_asfg",
            "original_asfg_unshared"]
    LABEL = {
        "original": ("Referenced STLAT", "shared", "static"),
        "original_unshared": ("\\quad + separate $W_x$", "separate", "static"),
        "original_asfg": ("Referenced STLAT + ASFG", "shared", "ASFG"),
        "original_asfg_unshared": ("\\quad + separate $W_x$", "separate", "ASFG"),
    }
    for i, k in enumerate(WANT):
        if k not in a:
            continue
        r = a[k]
        nm, share, fuse = LABEL[k]
        bold = "\\textbf{%s}" if k == "original_asfg_unshared" else "%s"
        L.append("%s & %s & %s & %s & %s & %s\\\\"
                 % (bold % nm, share, num(r.get("tau_overlap")),
                    num(r.get("coherence")), num(r.get("eff_rank_frac")),
                    pct(r["mean"])))
        if i == 1:
            L.append("\\midrule")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(L) + "\n"


def texlabel(k):
    """Arm names come from experiment JSON and contain raw LaTeX hazards."""
    t = k.strip()
    t = t.replace("W_x", "$W_x$").replace("M_t", "$M_t$").replace("C_t", "$C_t$")
    t = t.replace("tau", "$\\tau$")
    # any surviving underscore is a literal, not a subscript
    out, i = [], 0
    while i < len(t):
        if t[i] == "$":
            j = t.find("$", i + 1)
            j = len(t) - 1 if j < 0 else j
            out.append(t[i:j + 1]); i = j + 1
        else:
            out.append("\\_" if t[i] == "_" else t[i]); i += 1
    return "".join(out)


# ----------------------------------------------------------------------
# Table 2 -- ISL, paired, and honestly non-significant
# ----------------------------------------------------------------------


def table_negative(diag, ratio):
    L = ["% AUTO-GENERATED by tools/make_tables.py -- do not edit",
         "\\begin{table}[htb]", "\\centering",
         "\\caption{A negative result, reported in full. Constraining each "
         "memory to a disjoint timescale band (Section~\\ref{sec:negative}) "
         "does \\emph{not} improve accuracy: it is far worse than an ordinary "
         "free-gate memory, and the deficit widens as the two required "
         "timescales separate, which is the opposite of what a coverage argument "
         "predicts. The bands occupy their intended ranges (median $\\tau$ per "
         "band $1.7$, $4.8$, $13.4$, $38.0$), so this is not a coverage "
         "failure. The explanation is that per-unit gates already supply "
         "timescale diversity, and hard tiling buys that diversity by removing "
         "capacity.}",
         "\\label{tab:negative}", "\\footnotesize",
         "\\begin{tabular}{@{}lcccc@{}}", "\\toprule",
         "\\textbf{Memory} & $\\tau_l/\\tau_s{=}2$ & $4$ & $8$ & $14$\\\\",
         "\\midrule"]
    rows = {r["ratio"]: r for r in ratio["rows"]}
    ks = [2, 4, 8, 14]
    L.append("Free per-unit gates ($K{=}1$) & " + " & ".join(
        pct(rows[k]["spectral_K1"]["acc_mean"]) if k in rows else "--" for k in ks) + "\\\\")
    L.append("Tiled disjoint bands ($K{=}4$) & " + " & ".join(
        pct(rows[k]["spectral"]["acc_mean"]) if k in rows else "--" for k in ks) + "\\\\")
    L.append("\\midrule")
    L.append("Difference & " + " & ".join(
        ("$-$" + pct(rows[k]["spectral_K1"]["acc_mean"] - rows[k]["spectral"]["acc_mean"]))
        if k in rows else "--" for k in ks) + "\\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(L) + "\n"


# ----------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default=os.path.join("out", "tables"))
    a = ap.parse_args()

    pos = load(os.path.join(a.results, "collapse_final.json"))
    ratio = load(os.path.join(a.results, "ratio_synthetic.json"))
    diag = load(os.path.join(a.results, "diagnose.json"))
    os.makedirs(a.out, exist_ok=True)
    written = []
    if pos:
        open(os.path.join(a.out, "collapse.tex"), "w", encoding="utf-8").write(
            table_collapse(pos)); written.append("collapse.tex")
    if ratio:
        open(os.path.join(a.out, "negative.tex"), "w", encoding="utf-8").write(
            table_negative(diag, ratio)); written.append("negative.tex")
    print("tables written : %s" % ", ".join(written))


if __name__ == "__main__":
    main()
